version: 1
disable_existing_loggers: no

formatters :
  simple:
    format: '%(asctime)s [%(levelname)s]  %(funcName)s() : %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  hourly :
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: H
    interval: 1
    utc: True
    filename: /home/song/logs/hourly.log

  daily :
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: midnight
    interval: 1
    utc: True
    filename: /home/song/logs/daily.log

root:
    level: INFO
    handlers: [console,daily,hourly]

loggers:
  aposong :
    level: DEBUG
    handlers: [console,daily]
    propagate: no

    
