create table weather_station (
	weather_station_id    bigserial primary key,    
	davis_out_temp	        real    ,
	davis_dew_point	        real    ,
	davis_windchill		real    ,
	davis_in_hum		real    ,
	davis_out_hum		real    ,
	davis_wind_dir		real	,
	davis_wind_speed        real	,
	davis_pressure	 	real	,
	davis_pressure_trend	varchar	,
	davis_daily_rain	real	,       
	davis_total_rain	real	, 
	davis_rain_rate		real	,
	davis_storm_rain	int	,
	davis_high_rain_rate_hour	int,
	davis_forecast		varchar	,
	davis_solar_rad		real	,
	davis_lastupdate	bigint	,
	davis_timestamp		timestamp,
	bw_sky_temp		real	,
	bw_amb_temp		real	,
	bw_sensor_temp		real	,
	bw_wind_speed		real	,
	bw_hum			real	,
	bw_dew_point		real	,
	bw_cloud_condition	int	,
	bw_cloud_str		varchar ,
	bw_lastupdate		bigint	,
	bw_timestamp		timestamp,
	extra_1			real	,
	extra_2			real	,
	extra_3			int	,
	extra_4			int	,
	extra_5			varchar	,	
	ins_at               timestamp  not null,
	bw_rain_cond		int
);
