create table motors (
	motors_id       bigserial primary key,    
	iodine_pos           	 int        not null,
	eng_pos	       		 int    not null,
	calib_mirror_pos	 int    not null,
	mirror_slide	 	 int    ,
	spectrograph_foc	 int    ,
	slit_pos	 	 int    ,
	iodine_temp_set	 	 real    ,
	iodine_temp_read	 real    ,
	iodine_heater_on	 int    ,
	iodine2_temp_read	 real    ,
	iodine2_heater_on	 real    ,
	lamp_halogen_on	 	 int    ,
	lamp_thar_on	 	 int    ,
	lamp_optional_on	 int,
	lamp_optional2_on	 int,
	lamp_optional3_on	 int,
	fabry_perot_on	 	 int       ,
	fibre_slide		 int       ,
	nasmyth_slide	 	 int       ,	
	image_derotator_angle	 real       ,
	image_derotator_orientation	 real       ,
	image_derotator_tracking	 int       ,
	adc_angle_1		 real       ,
	adc_angle_2		 real       ,
	adc_tracking		 int,
	filter_wheel_red_pos	 int       ,
	filter_wheel_vis_pos	 int       ,
	beam_selector	 	 int       ,
	solar_shutter	 	 int,
	pst_motor_8		 int,
	nas_motor_2		 int,
	extra_val_1		 real,
	extra_val_2		 real,
	extra_val_3		 int,
	extra_val_4		 int,
	extra_param_1		 varchar,
	extra_param_2		 varchar,
	ins_at                   timestamp  not null
);

