create table obs_request_4 (
        req_no          serial primary key,
        req_prio        int not null,
        pre_obs_spec_id int,
        right_ascension double precision,
        declination     double precision,
        epoch           real,
        ra_pm           real,
        dec_pm          real,
        magnitude       real,
        object_name     varchar(64),
        imagetype       varchar(16) not null,
        project_name    varchar(128) not null,
        project_id      int not null,
        observer        varchar,
        binning         int,
        x_begin         int,
        y_begin         int,
        x_end           int,
        y_end           int,
        no_exp          int not null,
        no_target_exp   int,
        no_thar_exp     int,
        iodine_cell     int,
        obs_mode        varchar,
        exp_time        real not null,
        start_window    timestamp not null,
        stop_window     timestamp not null,
        delay           int,
        telescope       int,
        constraint_1        int,
        constraint_2        real,
        constraint_3        varchar,
        extra_param_1        int,
        extra_param_2        real,
        extra_param_3        real,
        extra_param_4        varchar,
        extra_param_5        varchar,        
        ins_at          timestamp not null default current_timestamp
);
