create table tel_dome (
    tel_dome_id bigserial primary key NOT NULL,
    tel_power_state integer,
    tel_con_state boolean,
    tel_motion_state integer,
    tel_on_target boolean,
    tel_tracking boolean,
    tel_ra_j2000_str character varying ,
    tel_dec_j2000_str character varying ,
    tel_ra_j2000 real,
    tel_dec_j2000 real,
    tel_ra_str character varying ,
    tel_dec_str character varying ,
    tel_ra real,
    tel_dec real,
    tel_alt real,
    tel_azm real,
    tel_zd real,
    tel_alt_rms_error real,
    tel_azm_rms_error real,
    tel_alt_motor_error integer,
    tel_alt_motor_err_str character varying,
    tel_azm_motor_error integer,
    tel_azm_motor_err_str character varying,
    azm_motor_enabled boolean,
    alt_motor_enabled boolean,
    pm character varying ,
    is_finding_home boolean,
    encoders_set boolean,
    field_rotation real,
    m3_con_state boolean,
    m3_pos integer,
    m3_moving boolean,
    obj_ra_j2000_str character varying,
    obj_dec_j2000_str character varying,
    dome_state integer,
    dome_shutter_1 integer,
    dome_shutter_2 integer,
    dome_light_state integer,
    temp_m1 real,
    temp_m2 real,
    temp_m3 real,
    temp_back real,
    temp_amb real,
    humidity real,
    dehum_state integer,
    fans_state boolean,
    focuser_1_con_state boolean,
    focuser_1_pos integer,
    focuser_1_moving boolean,
    focuser_1_complete boolean,
    derotator_1_con_state boolean,
    derotator_1_pos real,
    derotator_1_state integer,
    derotator_1_active boolean,
    focuser_2_con_state boolean,
    focuser_2_pos integer,
    focuser_2_moving boolean,
    focuser_2_complete boolean,
    derotator_2_con_state boolean,
    derotator_2_pos real,
    derotator_2_state integer,
    derotator_2_active boolean,
    tel_utc timestamp without time zone,
    tel_lst character varying,
    tel_jd real,
    overall_obs_state integer,
    extra_param_1 character varying,
    extra_param_2 character varying,
    extra_param_3 character varying,
    extra_param_4 character varying,
    extra_param_5 character varying,
    extra_val_1 integer,
    extra_val_2 integer,
    extra_val_3 real,
    extra_val_4 real,
    extra_val_5 real,
    tel_ready_state integer,
    tel_global_state integer,
    tel_ra_offset real,
    tel_dec_offset real,
    tel_alt_offset real,
    tel_az_offset real,
    ins_at timestamp without time zone NOT NULL
);
