create table tel_dome (
    tel_dome_id bigserial primary key NOT NULL,
    tel_con_state boolean,
    tel_tracking boolean,
    tel_ra_j2000 real,
    tel_dec_j2000 real,
    tel_ra real,
    tel_dec real,
    tel_alt real,
    tel_azm real,
    tel_alt_rms_error real,
    tel_azm_rms_error real,
    m3_pos integer,
    dome_shutterstate integer,
    dome_az real,
    dome_slewing boolean,
    dome_light_state boolean,
    temp_m1 real,
    temp_m2 real,
    temp_m3 real,
    temp_back real,
    temp_amb real,
    focuser_1_pos integer,
    focuser_1_moving boolean,
    focuser_2_pos integer,
    focuser_2_moving boolean,
    tel_lst character varying,
    ins_at timestamp without time zone NOT NULL
);
